### PR TITLE
add new build for influxdb 0.9.2

### PR DESCRIPTION
**Pull request by cscetbon**
Really needed to fix  https://github.com/influxdb/influxdb/commit/a3ab0939967f1fc93c4035e0fc743420c3488ed2

### CODE REVIEW

**Comment by 0x46616c6b** [comment]
Thanks for the PR! Are you only changed the loaded binary?

**Comment by 0x46616c6b** [comment]
I tested it in short locally and it seems to work.

**Comment by cscetbon** [comment]
@0x46616c6b yeah only. There should be a better way to share the same code but it works :)

**Comment by 0x46616c6b** [comment]
Of course there is a big duplication of the configuration, but for me it is the safest way to run not in regressions.

**Comment by 0x46616c6b** [comment]
So, the image is successfully built on Docker Hub. Thanks for your quick response!

**Pull request merged**
